# Generated by Django 6.0.1 on 2026-02-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ImageField(default=3, upload_to='categories/'),
            preserve_default=False,
        ),
    ]
