# Generated by Django 6.0.1 on 2026-02-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_variants',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='values',
            field=models.ManyToManyField(blank=True, to='app.value'),
        ),
    ]
